[package]
name = "automerge-repo"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
automerge = { version = "^0.3" }
uuid = { version = "1.2.2"}
tokio = { version = "1.27", features = ["full"] }
crossbeam-channel = { version = "0.5.8" }
parking_lot = { version = "0.12.1" }
futures = { version = "0.3.28" }
axum = { version = "0.6.18" }
reqwest = { version = "0.11.17", features = ["json"] }
serde = { version = "1.0.160", features = ["derive"]}
clap = { version = "4.2.5", features = ["derive"] }